# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors # This is the default value
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true
        formats:
            json: true
            xml: false
            rss: false
        mime_types:
            json: ['application/json', 'application/x-json']
    format_listener:
        enabled: true
        rules:
            - { path: '^/', prefer_extension: true, fallback_format: json, priorities: [ json ] }
