App\Entity\Article:
    exclusion_policy: all
    relations:
        - rel: self
          href:
              route: api_get_article
              parameters:
                  id: expr(object.getUuid())
                  _format: json
              absolute: false
          exclusion:
              groups: [ hateoas ]
        - rel: cover
          embedded: expr(service('app.article_service').getCover(object, true))
          exclusion:
              exclude_if: expr(object.getCoverFilename() === null)
              groups: [ hateoas, article ]
    properties:
        title:
            expose: true
            groups: [ article ]
        content:
            expose: true
            groups: [ article ]
        link:
            expose: true
            groups: [ article ]
        author:
            expose: true
            groups: [ article.user ]
        comments:
            expose: true
            groups: [ article.comments ]
    virtual_properties:
        getUuid:
            serialized_name: id
            groups: [ article ]
        getAuthorName:
            serialized_name: authorName
            groups: [ article ]