App\Entity\Comment:
    exclusion_policy: all
    relations:
        - rel: self
          href:
              route: api_get_comment
              parameters:
                  id: expr(object.getUuid())
                  _format: json
              absolute: false
          exclusion:
              groups: [ hateoas ]
    properties:
        author:
            expose: true
            groups: [comment]
        text:
            expose: true
            type: array
            groups: [comment]
        email:
            expose: true
            groups: [comment]
    virtual_properties:
        getUuid:
            serialized_name: id
            groups: [ comment ]