App\Entity\User:
    exclusion_policy: all
    custom_accessor_order: [ id, email, firstName, lastName, fullName ]
    relations:
        - rel: self
          href:
              route: api_get_user
              parameters:
                  id: expr(object.getUuid())
                  _format: json
              absolute: false
          exclusion:
              groups: [ hateoas ]
    properties:
        email:
            expose: true
            groups: [user]
        roles:
            expose: true
            type: array
            groups: [user]
        firstName:
            expose: true
            groups: [user]
        lastName:
            expose: true
            groups: [user]
        articles:
            expose: true
            groups: [ user.articles ]
    virtual_properties:
        getUuid:
            serialized_name: id
            groups: [ user ]
        getFullName:
            serialized_name: fullName
            groups: [ user ]