version: '3.8'

services:
  database:
    build:
      context: docker/database
    labels:
      com.symfony.server.service-prefix: 'DATABASE'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/data:/var/lib/mysql

  #redis:
  #  build:
  #    context: docker/redis

  #rabbitmq:
  #  build:
  #    context: docker/rabbitmq

  mailhog:
    build:
      context: docker/mailhog
    labels:
      com.symfony.server.service-prefix: 'MAILER'

  php-fpm:
    build:
      context: docker/php-fpm
    depends_on:
      - database
  #    - redis
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-10.5.8
      - SYMFONY_PROJECT_DEFAULT_ROUTE_URL=
      - MAILER_DSN=smtp://mailhog:1025
  #    - RABBITMQ_DSN=amqp://guest:guest@rabbitmq:5672/%2f/messages
      - SYMFONY_DEFAULT_ROUTE_HOST=news-aggregator.local:8081
    volumes:
      - ./:/var/www

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    networks:
      default:
        aliases:
          - news-aggregator.local